### ISSUE TITLE
Cool Feature in -user

### ISSUE THREAD

**Issue by DuckMasterAl** [quacky-bot/git-project#20]
**Is your feature request related to a problem?** 
Yes, the cool feature is always "Maybe 🤔"
**What is the new feature?** 
Add some checks to get cool to yes/no and a website linked reason why you got it/didn't.
**Additional context** 
Checks (~~5~~ Changed to 4):
- Found at least 1 error with Quacky
- Voted or is a Staff/Donator/Special
- In the Support Server
- Made a suggestion that has been approved

Total Check Count:
- 0 - Not Cool
- 1 - Kind of Cool
- 2 - Cool
- 3-4 - Super

## **What needs to be worked on**
- [x] Remove the bot owner badge and replace it with the suggestion badge | #21
- [x] Merge the Suggestion and Bug badge to a "Contributor" badge on the main profile (separate in the badges command). | #22
- [x] Make the checks if you're cool or not in the command | #20 
- [x] Think of renaming it from "Cool" to something like "Community Level" | #20
